version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
      ###< doctrine/doctrine-bundle ###
  symfony:
    container_name: symfony
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - database

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data: ###< doctrine/doctrine-bundle ###
